services:
  - type: web
    name: devdesk-nexus-hub
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npx serve -s dist -l 10000
    plan: free
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_APP_NAME
        value: DevDesk Nexus Hub
      - key: VITE_APP_VERSION
        value: 1.0.0
      - key: VITE_APP_ENVIRONMENT
        value: production
      - key: VITE_API_BASE_URL
        value: /api/v1
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 